language: java

jdk: openjdk8

# Execute build in container-based environment.
sudo: false

branches:
  except:
  - gh-pages

env:
  global:
  - ANDROID_HOME=$HOME/android-sdk
  - ANDROID_BUILD_TOOLS=28.0.3
  - ANDROID_SDK=28
  # Add Android SDK tools to path.
  - PATH=$PATH:$ANDROID_HOME/tools:$ANDROID_HOME/tools/bin:$ANDROID_HOME/platform-tools:$ANDROID_HOME/emulator

before_install:
# Copy fake local.properties.
- cp ci/local.properties ./
# Decrypt secret files.
- ci/decrypt-secrets

# Install Android SDK before each build (if not already cached).
install: ci/android-install-sdk

stages:
- Install
- Build
- Lint
- Test
- Test Coverage

jobs:
  include:
  - stage: Build
    name: Assemble
    script: ci/android-assemble
  - stage: Test
    name: Lint
    script: ci/android-lint
  - name: Unit test
    script: ci/android-unit-tests
  #  - name: Integration test
  #    script: ci/android-integration-tests
  #    env: EMULATOR_ANDROID_SDK=25 EMULATOR_ABI=arm64-v8a
  #  - name: Integration test
  #    script: ci/android-integration-tests
  #    env: EMULATOR_ANDROID_SDK=21 EMULATOR_ABI=armeabi-v7a
  - stage: Coverage
    name: Test coverage
    script: ci/android-test-coverage
  allow_failures:
  - name: Integration test
matrix:
  fast_finish: true

# Use Travis CI's cache management
before_cache:
- rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
- rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
  # Android SDK
  - "$ANDROID_HOME"
  # Gradle dependencies
  - "$HOME/.gradle/caches/"
  - "$HOME/.gradle/wrapper/"
  # Android build cache (see http://tools.android.com/tech-docs/build-cache)
  - "$HOME/.android/build-cache"
  # Android AVDs
#  - $ANDROID_AVD_HOME
#  - $ANDROID_SDK_HOME\avd
#  - $HOME\.android\avd

before_deploy: ci/prepare-deployment
deploy:
# Upload App Bundle and APK to GitHub Releases.
- provider: releases
  api_key:
    secure: o0cgA+Z1Skr/TgnWsjQw/z79rlSP0vpXx2deFrUP3maHOAv5cuaqbEVVMr4/5uWYtrGDKsn2YTD+MZlRmwHuhf86i32WhXvESzD+l5cCTLwDqdXC8tpdw3KS2fgX7RhmIFEfuyQEwUzCsDZrGeQcnXXacxIG+qqZaPORkiM8asA15xoAZEVNn3ZubcLs+S0+uf1Y43c32ClzjGo41uHouYUduFv0gMMNxrNEpNM048v5D+omiEyX7LaQtWbNTbSwaW+mDTtvf6dPP2lPelWWfBGwtZM5dW8dOc6VKZuzuFFDkoQBQSNd/hCDuto0tH+H2JMPalYt2H0YXuu2XWA7xXRAwC9KxRNHGZD9PRItjso10k2ETt2mhlyWN4iKU3btqZp2HjFl+QuZv26iZt+fUkzrVMdGKJlLi1/iybsna6QuiNR8xr1C7jQPduAYH35UOqBrIcd5l7O9QemFJHkQNnPqkY3A+VTAM18tz2B9rAjPK2h7dkwla4NfxrGL6o+oMHWNTlZYuYdlfn5ymmsXXjB0Rp4v/7RcrBlcm2W+CMk+pXTwqC4bTL84pn66jcNDIc41VLu2QCUCSHmBMoOl7QpxQyUSOBlJilTXQ1pfhKkf3cj8MMwTVBG+ovPLLl69Rw5bCUjHKiFM+fLRdteED1Yd2cOfEkAt+1HPNaW+c5U=
  file:
  - "*/release/*.apk"
  - "*/release/*.aab"
  file_glob: true
  name: "Release $TRAVIS_TAG"
  draft: true
  on:
    repo: Crazy-Marvin/MetadataRemover
    branch: master
# Release on Google Play Store.
- provider: script
  script: ci/deploy-google-play
  on:
    repo: Crazy-Marvin/MetadataRemover
    branch: master
