name: CI
on: push
jobs:
  build:
    runs-on: macOS-10.14
    steps:
      - name: "📥 Check-out"
        uses: actions/checkout@v1
      - name: "🧪 Gradle Wrapper Validation"
        uses: gradle/wrapper-validation-action@v1
      - name: "🧰 Install JDK"
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
          java-package: jdk
      - name: "🧰 Install Android SDK"
        uses: malinskiy/action-android/install-sdk@release/0.0.5
        with:
          acceptLicense: yes
      - name: "📁 Copy local CI properties"
        run: cp ci/local.properties ./
      - name: "🏗 Build"
        run: ./gradlew assembleDebug
      - name: "🧪 Android LINT"
        run: ./gradlew lint
      - name: "🧪 Code coverage"
        run: ./gradlew jacocoTestReport
      - name: "🧪 Unit test"
        run: ./gradlew test
      - name: "🧪 Integration test"
        uses: malinskiy/action-android/emulator-run-cmd@release/0.0.5
        with:
          cmd: ./gradlew connectedAndroidTest
          api: 25
          tag: google_apis
          abi: x86
      - name: "📤 Upload code coverage"
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          yml: .codecov.yml
