name: Deploy
on:
  push:
    branches:
      - master
jobs:
  deploy:
    runs-on: macos-10.15
    steps:
      - name: "📥 Check-out"
        uses: actions/checkout@v1
      - name: "🧰 Install JDK"
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
          java-package: jdk
      - name: "🧰 Install Android SDK"
        uses: malinskiy/action-android/install-sdk@release/0.0.5
        with:
          acceptLicense: yes
      - name: "🕶 Decrypt secret files"
        run: |
          cd secret
          gpg --quiet --batch --yes --decrypt --passphrase="${{ secrets.FILES_PASSPHRASE }}" --output secrets.tar secrets.tar.gpg
          tar -xf secrets.tar
      - name: "📁 Copy local CI properties"
        run: cp ci/local.properties ./
      - name: "🏗 Build"
        run: ./gradlew assembleDebug
      - name: "🚀 GitHub release"
        run: ./gradlew githubRelease
      - name: "🚀 Google Play publish"
        run: ./gradlew publishRelease
